from bgl import *
from blf import *
def SetPoint(ps):glPointSize(ps)
def RstPoint():SetPoint(4.0)
def SetPointBlend(ps):SetPoint(ps);SetBlend()
def RstPointBlend():RstPoint();RstBlend()
def SetLine(lt):glLineWidth(lt)
def RstLine():SetLine(1.0)
def SetLineSmooth():glEnable(GL_LINE_SMOOTH)
def SetLineSBlend(lt):SetBlend();SetLineSmooth();SetLine(lt)
def RstLineSmooth():glDisable(GL_LINE_SMOOTH)
def RstLineSBlend():RstBlend();RstLineSmooth();RstLine()
def SetSRGB():glEnable(GL_FRAMEBUFFER_SRGB)
def SetBFuncAlphaZero():glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ZERO);glBlendEquation(GL_FUNC_ADD)
def SetBFuncOneAlpha():glEnable(GL_BLEND);glBlendFunc(GL_ONE,GL_ONE_MINUS_SRC_ALPHA);glBlendEquation(GL_FUNC_ADD)
def SetBFuncAlphaAlpha():glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);glBlendEquation(GL_FUNC_ADD)
def SetDefCoSpace():glEnable(GL_FRAMEBUFFER_DEFAULT)
def RstColorSpace():glDisable(GL_FRAMEBUFFER_SRGB)
def SetBlend():glEnable(GL_BLEND)
def RstBlend():glDisable(GL_BLEND)
def SetBlendAlpha():SetBlend();glBlendFunc(GL_ONE,GL_ONE_MINUS_SRC_ALPHA)
def SetDepth():glEnable(GL_DEPTH_TEST)
def RstDepth():glDisable(GL_DEPTH_TEST)
def SetFontColor(id,co=(1,1,1,1)):color(id,co)
def GetFontDim(id,txt):return dimensions(id,txt)
def SetFontShadow(id,off_x=-1,off_y=-2,lvl=3,co=(0,0,0,1)):enable(id,SHADOW);shadow(id,lvl,*co);shadow_offset(id,off_x,off_y)
def RstFontShadow(id):disable(id,SHADOW)
def SetFontWW(id,width):enable(id,WORD_WRAP);word_wrap(id,width)
def RstFontWW(id):disable(id,WORD_WRAP)
def SetFontClip(id,xi,xf,yi,yf):enable(id,CLIPPING);clipping(id,xi,xf,yi,yf)
def RstFontCLip(id):disable(id,CLIPPING)
def SetScissor(xi,xf,yi,yf):glEnable(GL_SCISSOR_TEST);glScissor(int(xi),int(xf),int(yi),int(yf))
def RstScissor():glDisable(GL_SCISSOR_TEST)
def SetFontRot(id,a):enable(id,ROTATION);rotation(id,a)
def RstFontRot(id):disable(id,ROTATION)
def SetFontSize(id,_size,_dpi):size(id,_size,_dpi)
def SetMultisample():glEnable(GL_MULTISAMPLE)