schema_version = "1.0.0"

id = "sculpt_paint_wheel"
version = "3.0.5"
name = "Sculpt+Paint Wheel"
tagline = "Radial wheel for sculpt and paint workflows"
maintainer = "J. Fran Matheu"
type = "add-on"

website = "https://github.com/jfranmatheu/Sculpt-Paint-Wheel"
tags = ["Interface", "Sculpt", "Paint"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  ".vscode/",
  "*.zip",
]
